In [122]:
def sessenfeld_criterion(A):
    
    n = A.shape[0]
    
    beta = np.zeros(n, dtype = float)
    beta[0] = np.absolute(A[0, 1:]).sum()/np.absolute(A[0,0])

    if beta[0] >= 1:
        return False 
    
    for i in np.arange(1, n):
        
        beta[i] = ((np.absolute(A[i, 0:i])*beta[0:i]).sum() + np.absolute(A[i, i+1:n+1]).sum())/np.absolute(A[i,i])
        
        if beta[i] >= 1:
            return False

    return beta.min()

In [181]:
def gauss_seidel( A, b, x0, tol, kmax = 10000, description = False):
    
    L = np.tril(A)
    R = np.triu(A, 1)
    
    C = - op.inversa(L).dot(R)
    g = op.inversa(L).dot(b)
    
    k = 0
    
    x = x0
    
    while la.norm(b - A.dot(x)) > tol and  k < kmax:
        
        k += 1
        
        x = C.dot(x) + g
    
    if description:
        
        beta = sessenfeld_criterion(A)
        
        print(f'The Left matrix: \n\n{L} \n\nThe Right matrix: \n\n{R}\n\n')
        
        print(f'The C matrix: \n\n{C} \n\nThe g vector: \n\n{g}\n\n')

        print(f'Sessenfeld Criterion Beta: {beta} \nNumber of iterations: {k} \nError: {la.norm(b - A.dot(x))}')
        
    return x

## **Questão 1**

In [174]:
A1 = np.array([
    [-4, 2, 1],
    [-1, 5, 2],
    [-1, -3, 6],
],dtype = float)

b1 = np.array([2, -4, 5], dtype = float)

In [175]:
A1

array([[-4.,  2.,  1.],
       [-1.,  5.,  2.],
       [-1., -3.,  6.]])

In [178]:
x01 = np.array([0, 0, 0])

In [179]:
x1 = gauss_seidel(A1, b1, x01,10**(-6), description = True)

The Left matrix: 

[[-4.  0.  0.]
 [-1.  5.  0.]
 [-1. -3.  6.]] 

The Right matrix: 

[[0. 2. 1.]
 [0. 0. 2.]
 [0. 0. 0.]]


The C matrix: 

[[-0.          0.5         0.25      ]
 [-0.          0.1        -0.35      ]
 [-0.          0.13333333 -0.13333333]] 

The G matrix: 

[-0.5 -0.9  0.3]


Sessenfeld Criterion Beta: 0.4000000000000001 
Number of iterations: 10 
Error: 4.3151183144609864e-07


In [183]:
print(f'Result x = {x1}')

Result x = [-0.99218748 -1.05468756  0.14062498]


## **Questão 2**

In [184]:
A2 = np.array([
    [5, -1, 0, 1],
    [0, 4, 3, 1],
    [1, 4, 5, 0],
    [0, 1, 3, 7],
],dtype = float)

b2 = np.array([4, 3, 2, 1], dtype = float)

In [185]:
A2

array([[ 5., -1.,  0.,  1.],
       [ 0.,  4.,  3.,  1.],
       [ 1.,  4.,  5.,  0.],
       [ 0.,  1.,  3.,  7.]])

In [188]:
x02 = np.array([0, 0, 0, 0])

In [189]:
x2 = gauss_seidel(A2, b2, x02,10**(-3), description = True)

The Left matrix: 

[[5. 0. 0. 0.]
 [0. 4. 0. 0.]
 [1. 4. 5. 0.]
 [0. 1. 3. 7.]] 

The Right matrix: 

[[ 0. -1.  0.  1.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


The C matrix: 

[[-0.          0.2        -0.         -0.2       ]
 [-0.         -0.         -0.75       -0.25      ]
 [-0.         -0.04        0.6         0.24      ]
 [-0.          0.01714286 -0.15       -0.06714286]] 

The g vector: 

[ 0.8   0.75 -0.36  0.19]


Sessenfeld Criterion Beta: False 
Number of iterations: 14 
Error: 0.0009076505893849079


In [191]:
print(f'Result x = {x2}')

Result x = [ 0.99659424  1.30013575 -0.83942745  0.31687808]


In [2]:
import numpy as np

In [3]:
import calc_num.operations as op

In [4]:
from numpy import linalg as la