In [36]:
def eliminacao_gauss(A, b):
    
    n = A.shape[0]
    
    U = np.copy(A)
    L = np.identity(n)
    
    bl = np.copy(b)
        
    for i in range(n - 1):
        for j in range(i+1, n):
            
            m = -U[j][i]/U[i][i]
            
            U[j] += m*U[i]
            
            bl[j] = m*bl[i]
            
            L[j][i] = -m
    
    return U, bl, L

In [354]:
def eliminacao_gauss_pivot(A, b):
    
    n = A.shape[0]
    
    U = np.copy(A)
    L = np.identity(n)
    P = np.identity(n)
    
    bl = np.copy(b)
    
    npivot = 0
    
    for i in range(n - 1):
        
        pivot = np.argmax(np.absolute(U[i:n+1, i]))
        pivot += i  
        
        if pivot != i:
            
            U[[i, pivot]] = U[[pivot, i]]
            L[[i, pivot], :i] = L[[pivot, i], :i]
            P[[i, pivot]] = P[[pivot, i]]
            
            bl[[i, pivot]] = bl[[pivot, i]] 
                
            npivot =+ 1
            
        for j in range(i+1, n):
            
            m = -U[j][i]/U[i][i]
            
            U[j] += m*U[i]
            
            bl[j] += m*bl[i]
            
            L[j][i] = -m
    
    return U, bl, L, P

In [363]:
A = np.array([[0, 4, 6], 
              [1, -3, -1],
              [2, 1, 1]], dtype = float)

b = np.array([8, 8, 7], dtype = float)

In [364]:
A

array([[ 0.,  4.,  6.],
       [ 1., -3., -1.],
       [ 2.,  1.,  1.]])

In [369]:
U, bl, L, P = eliminacao_gauss_pivot(A, b)

In [370]:
U

array([[2.  , 1.  , 1.  ],
       [0.  , 4.  , 6.  ],
       [0.  , 0.  , 3.75]])

In [371]:
L

array([[ 1.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ],
       [ 0.5  , -0.875,  1.   ]])

In [372]:
L.dot(U)

array([[ 2.,  1.,  1.],
       [ 0.,  4.,  6.],
       [ 1., -3., -1.]])

In [373]:
P.dot(A)

array([[ 2.,  1.,  1.],
       [ 0.,  4.,  6.],
       [ 1., -3., -1.]])

In [374]:
P

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [362]:
bl

array([7. , 8. , 7.5])

In [127]:
print((bl[0]-bl[1]/U[1][1])/U[1][1], bl[1]/U[1][1] )

-0.09999990000009601 1.9999976000028804e-07


In [53]:
L.dot(U)

array([[ 1.e-05,  1.e+01],
       [ 5.e+00, -6.e+00]])

In [1]:
import numpy as np