In [38]:
def gauss_jacobi( A, b, x0, tol, kmax = 10000):
    
    n = len(b)
    
    D = np.diag(np.diag(A))
    C = np.identity(n) - op.inversa(D).dot(A)
    g = op.inversa(D).dot(b)
    
    print(D)
    print(C)
    print(g)
    
    k = 0
    
    x = x0
    
    while la.norm(b - A.dot(x0)) > tol and  k < kmax:
        
        k += 1
        
        x = C.dot(x) + g
    
    return x
    

In [39]:
A = np.array([
    [10, 1, -1, 0],
    [1, 10, 0, 1],
    [2, -1, 10, 0],
    [0, 1, 1, -10]
],dtype = float)

b = np.array([13, 12, 11, 10], dtype = float)

In [40]:
A

array([[ 10.,   1.,  -1.,   0.],
       [  1.,  10.,   0.,   1.],
       [  2.,  -1.,  10.,   0.],
       [  0.,   1.,   1., -10.]])

In [41]:
x0 = np.array([0, 0, 0, 0])

In [42]:
r = gauss_jacobi(A, b, x0,10**(-3), kmax = 100 )

[[ 10.   0.   0.   0.]
 [  0.  10.   0.   0.]
 [  0.   0.  10.   0.]
 [  0.   0.   0. -10.]]
[[ 0.  -0.1  0.1  0. ]
 [-0.1  0.   0.  -0.1]
 [-0.2  0.1  0.   0. ]
 [ 0.   0.1  0.1  0. ]]
[ 1.3  1.2  1.1 -1. ]


In [43]:
r

array([ 1.28080986,  1.1508216 ,  0.95892019, -0.78902582])

In [44]:
def cl(A):
    
    n = A.shape[0]
    
    for i in np.arange(n):
        
        a = ( np.absolute(A[i,:]).sum() - np.absolute(A[i, i]) ) / np.absolute(A[i, i])
        
        if a >= 1:
            return False
        
    
    return True

In [45]:
def cc(A):
    
    n = A.shape[0]
    
    for i in np.arange(n):
        
        a = ( np.absolute(A[:,i]).sum() - np.absolute(A[i, i]) ) / np.absolute(A[i, i])
        
        if a >= 1:
            return False
        
    
    return True

In [46]:
cc(A)

True

In [47]:
import numpy as np

In [4]:
import calc_num.operations as op

In [23]:
from numpy import linalg as la