# Semana 5 Cálculo Numérico 

In [81]:
def lsti(T, b):
    
    n = len(b)
    
    x = np.zeros(n)
    
    for i in range(n):
      
        x[i] = ( b[i] - sum(T[i,:i]*x[:i]) )/T[i][i]
    
    return x

In [143]:
def lsts(T, b):
    
    n = len(b)
    
    x = np.zeros(n)
    
    for i in range(n-1,-1,-1):
        
        x[i] = ( b[i] - sum(T[i,i:n]*x[i:n]) )/T[i][i]
    
    return x

In [345]:
def LU(A):
    
    d = A.shape
    
    U = np.zeros(d)
    L = np.identity(d[0])
        
    for j in range(d[0]):
        
        for i in range(j+1):
            
            U[i][j] = A[i][j] - sum(L[i,:i]*U[:i,j])

        for i in range(j, d[0]):
            
            L[i][j] = (A[i][j] - sum(L[i,:j]*U[:j,j]))/(U[j][j])

    return L, U

In [359]:
T = np.array([[9, 0, 1, 2], [1, 8, 1, 1], [-2, 1, 5, 0], [3, 1, 0, 6]])
b = np.array([1, 3])

In [360]:
a = LU(T)
a[0].dot(a[1])

array([[ 9.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         2.00000000e+00],
       [ 1.00000000e+00,  8.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [-2.00000000e+00,  1.00000000e+00,  5.00000000e+00,
         0.00000000e+00],
       [ 3.00000000e+00,  1.00000000e+00,  2.19899246e-17,
         6.00000000e+00]])

In [361]:
a

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.11111111,  1.        ,  0.        ,  0.        ],
        [-0.22222222,  0.125     ,  1.        ,  0.        ],
        [ 0.33333333,  0.125     , -0.08695652,  1.        ]]),
 array([[9.        , 0.        , 1.        , 2.        ],
        [0.        , 8.        , 0.88888889, 0.77777778],
        [0.        , 0.        , 5.11111111, 0.34722222],
        [0.        , 0.        , 0.        , 5.26630435]]))

In [362]:
0.34722222/5.11111111

0.06793478218868147

In [352]:
x = linalg.lu(T)

In [354]:
x[1].dot(x[2])

array([[-2.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  2.00000000e+00, -5.55111512e-17]])

In [334]:
from scipy import linalg

In [335]:
import numpy as np